name: Extend supported logos

on:
  workflow_dispatch:
    inputs:
      type:
        description: "chains | symbols | api-providers | auto-clear"
        required: true
        type: choice
        options:
          - auto-clear
          - chains
          - symbols
          - api-providers
      value:
        description: "Comma separated values OR --clear (ignored when type=auto-clear)"
        required: false
        default: ""


permissions:
  contents: write

jobs:
  extend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.12.0
          cache: 'pnpm'

      - name: Install Packages  
        run: pnpm install

      - name: Extend extension.json
        run: |
          if [ "${{ inputs.type }}" = "auto-clear" ]; then
            node scripts/extend-json.js auto-clear
          else
            node scripts/extend-json.js "${{ inputs.type }}" "${{ inputs.value }}"
          fi
          
      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add extension.json
            git commit -m "chore: extend ${{ inputs.type }}" --no-verify --signoff
            git push
          else
            echo "No changes to commit"
          fi

